[versions]
# SLF4J releases: http://www.slf4j.org/news.html
slf4j = "2.0.6"

# Postgres JDBC releases: https://jdbc.postgresql.org/ and https://search.maven.org/artifact/org.postgresql/postgresql
postgres-jdbc = "42.5.1"


[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
postgres-jdbc = { module = "org.postgresql:postgresql", version.ref = "postgres-jdbc" }
